/**
 * generate-idf-facts.ts — P3.2
 *
 * Writes data/idf-facts.generated.ts: public, checkable facts per Île-de-France
 * commune used by the Tier B content generator and the Tier A pages:
 *   - EPCI (intercommunalité) name and surface (km²), from geo.api.gouv.fr
 *     (INSEE COG); Paris arrondissements from the arrondissement-municipal type.
 *   - Whether the commune is inside the ZFE perimeter of the Métropole du
 *     Grand Paris (communes located inside the A86; source list below).
 *
 * Usage: npx tsx scripts/generate-idf-facts.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { allDepartments } from '../lib/locations-national';
import { IDF_DEPT_SLUGS } from '../lib/idf';

interface ApiCommune {
  nom: string;
  code: string;
  codeDepartement?: string;
  surface?: number;
  epci?: { code: string; nom: string };
}

/**
 * Communes inside the ZFE perimeter of the Métropole du Grand Paris (inside
 * the A86), as published by the Métropole and relayed by Crit'Air guides.
 * Sources: metropolegrandparis.fr (FAQ ZFE) ; lavignettecritair.fr/zfe/paris/villes-grand-paris.
 * TODO(owner): re-verify against metropolegrandparis.fr before publishing —
 * a law abolishing ZFEs was voted in April 2026 and awaits promulgation.
 */
const ZFE_COMMUNES: Record<string, string[]> = {
  '75': ['Paris'],
  '92': [
    'Antony', 'Asnières-sur-Seine', 'Bagneux', 'Bois-Colombes', 'Boulogne-Billancourt', 'Bourg-la-Reine',
    'Châtenay-Malabry', 'Châtillon', 'Chaville', 'Clichy', 'Colombes', 'Courbevoie', 'Fontenay-aux-Roses',
    'Garches', 'Gennevilliers', 'Issy-les-Moulineaux', 'La Garenne-Colombes', 'Le Plessis-Robinson',
    'Levallois-Perret', 'Malakoff', 'Marnes-la-Coquette', 'Meudon', 'Montrouge', 'Nanterre', 'Neuilly-sur-Seine',
    'Puteaux', 'Rueil-Malmaison', 'Saint-Cloud', 'Sceaux', 'Sèvres', 'Suresnes', 'Vanves', 'Vaucresson', "Ville-d'Avray",
  ],
  '93': [
    'Aubervilliers', 'Bagnolet', 'Bobigny', 'Bondy', 'Drancy', "L'Île-Saint-Denis", 'La Courneuve',
    'Le Pré-Saint-Gervais', 'Les Lilas', 'Montreuil', 'Noisy-le-Sec', 'Pantin', 'Romainville', 'Rosny-sous-Bois',
    'Saint-Denis', 'Saint-Ouen-sur-Seine',
  ],
  '94': [
    'Alfortville', 'Arcueil', 'Cachan', 'Champigny-sur-Marne', 'Charenton-le-Pont', 'Chevilly-Larue', 'Choisy-le-Roi',
    'Créteil', 'Fontenay-sous-Bois', 'Fresnes', 'Gentilly', 'Ivry-sur-Seine', 'Joinville-le-Pont', "L'Haÿ-les-Roses",
    'Le Kremlin-Bicêtre', 'Maisons-Alfort', 'Nogent-sur-Marne', 'Rungis', 'Saint-Mandé', 'Saint-Maurice', 'Thiais',
    'Villejuif', 'Vincennes', 'Vitry-sur-Seine',
  ],
};

const norm = (s: string) =>
  s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return (await res.json()) as T;
}

async function main() {
  const communes = await fetchJson<ApiCommune[]>(
    'https://geo.api.gouv.fr/communes?codeRegion=11&fields=nom,code,codeDepartement,surface,epci&format=json'
  );
  const arrondissements = await fetchJson<ApiCommune[]>(
    'https://geo.api.gouv.fr/communes?codeDepartement=75&type=arrondissement-municipal&fields=nom,code,surface&format=json'
  );
  const byInsee = new Map<string, ApiCommune>();
  communes.forEach(c => byInsee.set(c.code, c));
  const paris = byInsee.get('75056');
  arrondissements.forEach(a => byInsee.set(a.code, { ...a, epci: paris?.epci }));

  const zfe = new Set<string>();
  Object.entries(ZFE_COMMUNES).forEach(([dept, names]) => names.forEach(n => zfe.add(`${dept}|${norm(n)}`)));

  const rows: string[] = [];
  let missing = 0;
  let zfeCount = 0;
  const zfeMatched = new Set<string>();
  for (const dept of allDepartments.filter(d => IDF_DEPT_SLUGS.includes(d.slug))) {
    for (const city of dept.cities) {
      const api = city.insee ? byInsee.get(city.insee) : undefined;
      if (!api) {
        missing++;
        continue;
      }
      const inZfe = dept.code === '75' || zfe.has(`${dept.code}|${norm(city.name)}`);
      if (inZfe) {
        zfeCount++;
        zfeMatched.add(`${dept.code}|${norm(city.name)}`);
      }
      const surfaceKm2 = api.surface ? Math.round(api.surface / 100 * 10) / 10 : null; // API gives hectares
      rows.push(
        `  '${dept.slug}/${city.slug}': { epci: ${JSON.stringify(api.epci?.nom ?? null)}, surfaceKm2: ${surfaceKm2}, zfe: ${inZfe} },`
      );
    }
  }
  const unmatchedZfe = Array.from(zfe).filter(k => !zfeMatched.has(k) && !k.startsWith('75|'));

  const out = `// AUTO-GENERATED by scripts/generate-idf-facts.ts — do not edit.
// Public facts per Île-de-France commune (key: '<deptSlug>/<citySlug>').
// Sources: geo.api.gouv.fr (INSEE COG: EPCI, surface) ; Métropole du Grand
// Paris — périmètre ZFE (communes situées à l'intérieur de l'A86).
// Generated: ${new Date().toISOString().slice(0, 10)}

export interface IdfCommuneFacts {
  /** Intercommunalité (EPCI) name, e.g. "Métropole du Grand Paris". */
  epci: string | null;
  /** Commune surface in km² (INSEE). */
  surfaceKm2: number | null;
  /** Inside the ZFE perimeter of the Métropole du Grand Paris. */
  zfe: boolean;
}

export const idfCommuneFacts: Record<string, IdfCommuneFacts> = {
${rows.join('\n')}
};

export function getIdfCommuneFacts(deptSlug: string, citySlug: string): IdfCommuneFacts | null {
  return idfCommuneFacts[\`\${deptSlug}/\${citySlug}\`] ?? null;
}
`;
  const file = path.join(process.cwd(), 'data', 'idf-facts.generated.ts');
  fs.writeFileSync(file, out);
  console.log(`✅ ${rows.length} communes written (${missing} without INSEE match, ${zfeCount} in ZFE)`);
  if (unmatchedZfe.length) console.log(`⚠ ZFE names not matched in data: ${unmatchedZfe.join(', ')}`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
