/**
 * generate-idf-transport.ts — rail stations per Île-de-France commune (S2.2).
 *
 * Source: Île-de-France Mobilités open data, « Emplacement des gares IDF »
 * (https://data.iledefrance-mobilites.fr/explore/dataset/emplacement-des-gares-idf/,
 * licence ODbL) — every RER / Transilien / métro / tramway / VAL station with
 * its line ("res_com") and coordinates. The commune of each station is
 * resolved with geo.api.gouv.fr (reverse lookup on the station point), then
 * mapped to our (deptSlug, citySlug) pairs through the INSEE code of
 * lib/locations-national.ts.
 *
 * Output: data/idf-transport.generated.ts — for each commune the list of
 * lines and stations, used by the Tier B/C generator to state a verifiable
 * transport fact ("desservie par le RER D, gare de Combs-la-Ville – Quincy").
 *
 * Usage: npx tsx scripts/generate-idf-transport.ts   (results cached in
 * seo-audit/idf-stations.json so re-runs need no network).
 */
import * as fs from 'fs';
import * as path from 'path';
import { regions } from '../lib/locations-national';

const API = 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/emplacement-des-gares-idf/records';
const CACHE = path.join(process.cwd(), 'seo-audit', 'idf-stations.json');
const IDF_REGION = 'ile-de-france';

interface Station { name: string; line: string; mode: string; lat: number; lon: number; insee?: string }

async function fetchStations(): Promise<Station[]> {
  if (fs.existsSync(CACHE)) return JSON.parse(fs.readFileSync(CACHE, 'utf8'));
  const out: Station[] = [];
  for (let offset = 0; ; offset += 100) {
    const res = await fetch(`${API}?limit=100&offset=${offset}`);
    if (!res.ok) throw new Error(`IDFM API ${res.status}`);
    const data = await res.json() as { results: Array<Record<string, unknown>> };
    if (!data.results.length) break;
    for (const r of data.results) {
      const p = r.geo_point_2d as { lat: number; lon: number } | null;
      if (!p || !r.res_com || !r.nom_zdc) continue;
      out.push({ name: String(r.nom_zdc), line: String(r.res_com), mode: String(r.mode), lat: p.lat, lon: p.lon });
    }
    if (data.results.length < 100) break;
  }
  // Reverse-geocode each station point → INSEE commune code.
  for (const s of out) {
    try {
      const res = await fetch(`https://geo.api.gouv.fr/communes?lat=${s.lat}&lon=${s.lon}&fields=code&format=json`);
      const arr = await res.json() as Array<{ code: string }>;
      if (arr[0]) s.insee = arr[0].code;
    } catch { /* left without commune */ }
    await new Promise(r => setTimeout(r, 40));
  }
  fs.mkdirSync(path.dirname(CACHE), { recursive: true });
  fs.writeFileSync(CACHE, JSON.stringify(out));
  return out;
}

const MODE_LABEL: Record<string, string> = { RER: 'RER', TRAIN: 'Transilien', METRO: 'métro', TRAMWAY: 'tramway', VAL: 'navette automatique' };

(async () => {
  const stations = await fetchStations();
  const byInsee = new Map<string, Station[]>();
  for (const s of stations) if (s.insee) byInsee.set(s.insee, [...(byInsee.get(s.insee) || []), s]);

  const idf = regions.find(r => r.slug === IDF_REGION)!;
  const rows: string[] = [];
  let communes = 0;
  for (const d of idf.departments) for (const c of d.cities) {
    const list = c.insee ? byInsee.get(c.insee) : undefined;
    // Paris arrondissements share the commune code 75056 → resolved by arrondissement code 751xx.
    const arr = c.insee && /^751\d\d$/.test(c.insee) ? byInsee.get(c.insee) : undefined;
    const st = arr ?? list;
    if (!st || !st.length) continue;
    // One entry per line, first station name kept, modes normalised.
    const seen = new Map<string, { line: string; mode: string; station: string }>();
    for (const s of st) if (!seen.has(s.line)) seen.set(s.line, { line: s.line, mode: MODE_LABEL[s.mode] ?? s.mode.toLowerCase(), station: s.name });
    const entries = Array.from(seen.values()).sort((a, b) => a.line.localeCompare(b.line));
    rows.push(`  '${d.slug}/${c.slug}': [${entries.map(e => `{ line: ${JSON.stringify(e.line)}, mode: ${JSON.stringify(e.mode)}, station: ${JSON.stringify(e.station)} }`).join(', ')}],`);
    communes++;
  }
  const out = `// AUTO-GENERATED by scripts/generate-idf-transport.ts — do not edit.
// Rail stations per Île-de-France commune, keyed '<deptSlug>/<citySlug>'.
// Source: Île-de-France Mobilités open data « Emplacement des gares IDF »
// (licence ODbL), communes resolved via geo.api.gouv.fr.
// Generated: ${new Date().toISOString().slice(0, 10)} — ${stations.length} stations, ${communes} communes served.

export interface IdfTransportLine {
  /** Commercial line name, e.g. "RER D", "TRAM 5", "METRO 13", "TRAIN J". */
  line: string;
  /** Human mode: RER, Transilien, métro, tramway, navette automatique. */
  mode: string;
  /** One station of that line in the commune. */
  station: string;
}

export const idfTransport: Record<string, IdfTransportLine[]> = {
${rows.join('\n')}
};
`;
  fs.writeFileSync(path.join(process.cwd(), 'data/idf-transport.generated.ts'), out);
  console.log(`stations ${stations.length}, with commune ${stations.filter(s => s.insee).length}, communes served ${communes}`);
})();
