/**
 * generate-prefectures.ts — the préfectures and sous-préfectures of France,
 * from the official INSEE Code officiel géographique (D3).
 *
 * Sources (COG 2025, insee.fr/fr/information/8377162):
 *   - v_departement_<year>.csv  : CHEFLIEU = INSEE code of the préfecture
 *   - v_arrondissement_<year>.csv: CHEFLIEU = INSEE code of the chef-lieu
 *     d'arrondissement (sous-préfecture, or the préfecture itself)
 *
 * The INSEE codes are mapped to our (deptSlug, citySlug) pairs through the
 * `insee` field of lib/locations-national.ts. Paris/Lyon/Marseille are
 * chef-lieux as whole communes (75056, 69123, 13055): all their
 * arrondissement pages are marked.
 *
 * Usage: npx tsx scripts/generate-prefectures.ts [--year=2025]
 * Writes data/prefectures.generated.ts.
 */
import * as fs from 'fs';
import * as path from 'path';
import { regions } from '../lib/locations-national';

const YEAR = (process.argv.find(a => a.startsWith('--year=')) || '--year=2025').split('=')[1];
const BASE = 'https://www.insee.fr/fr/statistiques/fichier/8377162';

async function csv(name: string): Promise<Record<string, string>[]> {
  const res = await fetch(`${BASE}/${name}`, { headers: { 'User-Agent': 'Mozilla/5.0 (lesepavistespro build)' } });
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const text = await res.text();
  const lines = text.trim().split(/\r?\n/);
  const headers = lines[0].split(',').map(h => h.replace(/"/g, ''));
  return lines.slice(1).map(l => {
    const cells = l.match(/("([^"]*)"|[^,]*)(,|$)/g)!.map(c => c.replace(/,$/, '').replace(/^"|"$/g, ''));
    return Object.fromEntries(headers.map((h, i) => [h, cells[i] ?? '']));
  });
}

(async () => {
  const deps = await csv(`v_departement_${YEAR}.csv`);
  const arrs = await csv(`v_arrondissement_${YEAR}.csv`);
  const prefectures = new Map<string, string>(); // insee → dept code
  const sousPrefectures = new Map<string, string>();
  for (const d of deps) prefectures.set(d.CHEFLIEU, d.DEP);
  for (const a of arrs) if (!prefectures.has(a.CHEFLIEU)) sousPrefectures.set(a.CHEFLIEU, a.DEP);

  // insee → [{ deptSlug, citySlug, name }] (Paris/Lyon/Marseille expand to arrondissements)
  const byInsee = new Map<string, Array<{ deptSlug: string; citySlug: string; name: string }>>();
  const add = (k: string, v: { deptSlug: string; citySlug: string; name: string }) => byInsee.set(k, [...(byInsee.get(k) || []), v]);
  for (const r of regions) for (const d of r.departments) for (const c of d.cities) {
    if (!c.insee) continue;
    const entry = { deptSlug: d.slug, citySlug: c.slug, name: c.name };
    add(c.insee, entry);
    if (/^751\d\d$/.test(c.insee)) add('75056', entry);
    if (/^6938\d$/.test(c.insee)) add('69123', entry);
    if (/^132\d\d$/.test(c.insee)) add('13055', entry);
  }

  const rows: Array<{ key: string; name: string; insee: string; type: 'prefecture' | 'sous-prefecture'; dept: string }> = [];
  const missing: string[] = [];
  for (const [insee, dept] of prefectures) {
    const hits = byInsee.get(insee); if (!hits) { missing.push(`préfecture ${insee} (${dept})`); continue; }
    for (const h of hits) rows.push({ key: `${h.deptSlug}/${h.citySlug}`, name: h.name, insee, type: 'prefecture', dept });
  }
  for (const [insee, dept] of sousPrefectures) {
    const hits = byInsee.get(insee); if (!hits) { missing.push(`sous-préfecture ${insee} (${dept})`); continue; }
    for (const h of hits) rows.push({ key: `${h.deptSlug}/${h.citySlug}`, name: h.name, insee, type: 'sous-prefecture', dept });
  }
  rows.sort((a, b) => a.key.localeCompare(b.key));

  const out = `// AUTO-GENERATED by scripts/generate-prefectures.ts — do not edit.
// Préfectures and sous-préfectures of France (INSEE COG ${YEAR}: chef-lieux of
// departments and arrondissements), keyed '<deptSlug>/<citySlug>'.
// Generated: ${new Date().toISOString().slice(0, 10)} — ${prefectures.size} préfectures, ${sousPrefectures.size} sous-préfectures
// (${missing.length} chef-lieux without a page: ${missing.join(', ') || 'none'}).

export type PrefectureType = 'prefecture' | 'sous-prefecture';

export interface PrefectureEntry {
  name: string;
  insee: string;
  dept: string;
  type: PrefectureType;
}

export const prefectures: Record<string, PrefectureEntry> = {
${rows.map(r => `  '${r.key}': { name: ${JSON.stringify(r.name)}, insee: '${r.insee}', dept: '${r.dept}', type: '${r.type}' },`).join('\n')}
};
`;
  fs.writeFileSync(path.join(process.cwd(), 'data/prefectures.generated.ts'), out);
  console.log(`préfectures ${prefectures.size}, sous-préfectures ${sousPrefectures.size}, pages marked ${rows.length}, missing ${missing.length}`);
  missing.forEach(m => console.log('  missing:', m));
})();
